set nocompatible              " be iMproved
filetype off                  " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'altercation/vim-colors-solarized'
Bundle 'ervandew/supertab'
Bundle 'bling/vim-airline'

syntax on
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
